# Generated by Django 3.0.5 on 2022-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=45)),
                ('itemprice', models.FloatField(default=0)),
                ('itemimage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
